import { AbstractEventBus, AppEvent } from '@/lib/abstract-event-bus/AbstractEventBus';
import { v4 as uuidv4 } from 'uuid';
import { EventStatus } from './event.model';
import { eventRepository } from './event.repository';

export class FirestoreEventBusService extends AbstractEventBus {
  /**
   * Persists the event to Firestore.
   * This ensures the event is safely stored before we acknowledge success.
   */
  protected async deliver(event: AppEvent): Promise<void> {
    // We create the event record. The ID is auto-generated by create() if not provided.
    // However, repo.create expects an ID. We'll generate one.
    const id = uuidv4();

    await eventRepository.create(id, {
      topic: event.topic,
      payload: event.payload,
      traceId: event.metadata.traceId,
      actorId: event.metadata.actorId,
      orgId: event.metadata.orgId,
      status: EventStatus.PENDING,
      attempts: 0,
    });
  }
}

// Singleton Export
export const eventBus = new FirestoreEventBusService();
